# Simulator Configuration

[general]
channel_count       = 3
transmit_interval_ms = 1

[channel1]
port     = 5000
can_file = input/tx_CANFD_G2M-1_BUS.can

[channel2]
port     = 5001
can_file = input/tx_CANFD_G2M-2_BUS.can

[channel3]
port     = 5002
can_file = input/tx_CANFD_G5M_BUS.can